language: java
jdk:
- oraclejdk8
script:
- mvn javadoc:javadoc 
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_API_TOKEN
  on:
    branch: translation
cache:
  directories:
  - .autoconf
  - $HOME/.m2
